# Configuration de sponsoring GitHub (optionnel)
# Décommenter et adapter si vous souhaitez activer le sponsoring

# github: [guillaumecayeux]
# patreon: votre_username
# open_collective: geneweb-py
# ko_fi: votre_username
# custom: ['https://votre-site.com/donate']

